### ISSUE TITLE
Support CONTAINS operator

### ISSUE THREAD

**Issue by AvitalTamir** [AvitalTamir/cyphernetes#105]
In WHERE clauses, add support for the CONTAINS keyword that will do partial matches on strings

**Comment by naorpeled** [comment]
Hey @AvitalTamir,
I'll take this one

**Comment by AvitalTamir** [comment]
Thanks @naorpeled 👑

**Comment by jameskim0987** [comment]
Hi @naorpeled,  just checking in. How is your progress on this issue? If you are not working on it, I have some bandwidth to take care of it :) Let me know if you want to continue or I can take up on it.

**Comment by naorpeled** [comment]
> Hi @naorpeled,  just checking in. How is your progress on this issue? If you are not working on it, I have some bandwidth to take care of it :) Let me know if you want to continue or I can take up on it.

Hey!
I've been sick in last couple of days, planning on working on the task tomorrow
Sorry for the delay 🙏 

Will keep you posted if I need anything, I appreciate your offer!
