### ISSUE TITLE
Color escape codes are visible

### ISSUE THREAD

**Issue by dadav** [AvitalTamir/cyphernetes#131]
I'm using the kitty terminal and when I write `MATCH (d:D` it turns to `MATCH ([33md:D`. Is it possible to disable colors in the shell?

**Comment by AvitalTamir** [comment]
Hey @dadav thanks for reporting!
Will test this out with kitty and add add no-color mode support, regardless.

**Comment by AvitalTamir** [comment]
Thanks @naorpeled! let me know if you need anything.

**Comment by AvitalTamir** [comment]
In addition to a `--no-color` flag, we should also add support for [NO_COLOR](https://no-color.org)
