### ISSUE TITLE
add support for WHERE EXISTS

### ISSUE THREAD

**Issue by aetimmes** [AvitalTamir/cyphernetes#136]
I tried using cyphernetes to search for resources where a specific optional field was not set:

`cyphernetes query -A "MATCH (f:foo) WHERE f.spec.optionalField = null RETURN f.metadata.name"`

but receive `Error: unexpected IDENT` in response to this query.

I'd love to have a way to query for the existence of fields in some way.

**Comment by AvitalTamir** [comment]
Hey @aetimmes thanks for reporting! Good catch, indeed there is no way currently to compare against a null value. Adding this to the contents of the next release 🙏

**Comment by AvitalTamir** [comment]
Merged #138 which allows comparing against `null` (legal Cypher) using `= null` and `!= null`.
Will be included in the next (v0.14) release.
