### ISSUE TITLE
How to integrate Cyphernetes in a Go project? (Karpor)

### ISSUE THREAD

**Issue by elliotxx** [AvitalTamir/cyphernetes#146]
We're interested in integrating Cyphernetes as a query engine in our Kubernetes visualization tool Karpor (https://github.com/KusionStack/karpor/issues/644).

- Do you provide any Go SDK or client library for integration?
- Is there any integration documentation or examples we could reference?
- What would be your suggestions to get started with this integration?

Thanks for your help!

**Comment by AvitalTamir** [comment]
Hey @elliotxx thanks for opening the issue - I'm super excited about having Karpor support the Cyphernetes language and will work hard to push this effort forward!

The Cyphernetes monorepo contains a package called `parser` (which should probably be renamed to `core`) - this package contains the language parser, the relationship engine and the Kubernetes query engine.
The three Cyphernetes programs currently in existence (the CLI, web client and operator framework) all consume this package.
I think there's some work cut out for us here though - I think Karpor will be the first time integrating this into an existing program that provides its own K8s client.

I will reach out to you directly and let's try to set up a call after I get to get back to the related code and get an effort estimate.

**Comment by AvitalTamir** [comment]
Excellent, in the meantime I'll familiarize myself with the Karpor codebase and wrap my heads around the effort

**Comment by AvitalTamir** [comment]
Closing this, an effort to provide a clean interface to the language engine has been merged, a [migration guide](https://github.com/AvitalTamir/cyphernetes/blob/main/docs/INTEGRATION.md) has been added and we'll continue the conversation re. Karpor in other channels 💪

**Comment by elliotxx** [comment]
@AvitalTamir Bro, just shipped Karpor on PH - mind dropping by? 🙌 And, I think we can collaborate on PH in the future!
https://www.producthunt.com/posts/karpor

**Comment by AvitalTamir** [comment]
Definitely, going to support you guys there now :)

**Comment by elliotxx** [comment]
@AvitalTamir Thank you, brother. Please feel free to contact me if you need anything
