### ISSUE TITLE
How do I query for custom Kinds where I have two custom types with the same "Kind"

### ISSUE THREAD

**Issue by SleepyBrett** [AvitalTamir/cyphernetes#147]
I have clusters where we have multiple CRD Kinds, in different groups. When I try to query for say `releases.helm.crossplane.io` when there is another release, that seems to throw an error.

**Comment by AvitalTamir** [comment]
Indeed, we'll add support for fully qualified and a proper error message for ambiguous kinds in the next release.

Again - thanks for reporting 💪
