### ISSUE TITLE
[CLI] Add a version command

### ISSUE THREAD

**Issue by scraly** [AvitalTamir/cyphernetes#148]
In the CLI world it's a common usage and behavior to have a command printing the version of the CLI with `-v`and/or `version` command :).

```
$ cyphernetes
Cyphernetes allows you to query Kubernetes resources using a Cypher-like query language.

Usage:
  cyphernetes [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  operator    Manage the Cyphernetes operator
  query       Execute a Cypher-inspired query against Kubernetes
  shell       Launch an interactive shell
  web         Start the Cyphernetes web interface

Flags:
  -A, --all-namespaces     Query all namespaces
  -h, --help               help for cyphernetes
  -l, --loglevel string    The log level to use (debug, info, warn, error, fatal, panic) (default "info")
  -n, --namespace string   The namespace to query against (default "default")
      --no-color           Disable colored output in shell and query results

Use "cyphernetes [command] --help" for more information about a command.
```

In cyphernetes it seems that it does not exists.

**Comment by AvitalTamir** [comment]
Thanks for opening the issue @scraly, we'll add this to the upcoming release.

@naorpeled would you like to take this one?
Let's take it internally how we align the program version with the GitHub release.

**Comment by naorpeled** [comment]
> Thanks for opening the issue @scraly, we'll add this to the upcoming release.
> 
> @naorpeled would you like to take this one?
> Let's take it internally how we align the program version with the GitHub release.

Sure thing:)
