### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by AvitalTamir** [AvitalTamir/cyphernetes#76]
The preferred way for most (mac) users to install would be via `brew install cyphernetes`.

The project qualifies to be added to Homebrew according to the [Acceptable Formulae doc](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff) however it is frowned upon for solo devs to add their own work. If anybody would like to pick this up it would be much appreciated.

**Comment by anthonybrice** [comment]
I'd like to pick this up. I don't see cyphernetes in homebrew's PRs currently, so I'll try to get PR in there today.

**Comment by anthonybrice** [comment]
Hi @AvitalTamir. Do you have any suggestions for me regarding this? https://github.com/Homebrew/homebrew-core/pull/188365#discussion_r1758999432

**Comment by AvitalTamir** [comment]
@anthonybrice I'm AFK right now but I believe your answer there is correct, I'm not able to check right now but pretty sure this needs to be installed separately and exist on the path as you mentioned.

This was almost a year ago so I can't remember for sure, it's worth checking. If you need me to, I'll be able to try this with goyacc in the project dependencies in a few hours and let you know.

Thanks for the effort!

**Comment by AvitalTamir** [comment]
@anthonybrice I couldn't find a way to make this work without installing the goyacc binary like in your PR.
goyacc is an external dependency to the project, it's sources are not required to compile Cyphernetes.
Adding it to the dependencies file and installing dependencies doesn't add the goyacc binary anywhere to the system - which is required to generate the parser.
So I believe your PR does what is required.

**Comment by AvitalTamir** [comment]
I see this was merged 👏
Shall we close this issue? 

Would you like to make a PR for the README with updated installation instructions? 
I don't mind doing it myself, let me know what you prefer.

**Comment by AvitalTamir** [comment]
Thanks @anthonybrice - I'm closing this - I acknowledged your contribution in the README :)
Thank you so much again for doing this!
