### ISSUE TITLE
Add relationship between volumeattachments and persistentvolumes

### ISSUE THREAD

**Issue by dimm0** [AvitalTamir/cyphernetes#91]
Thanks!

**Comment by AvitalTamir** [comment]
Referencing #92

**Comment by AvitalTamir** [comment]
@dimm0 I'm also working on discovering relationships so it's automatic - but that is a handful and I want to support custom relationships before that. In any case - I'll add this in the meantime. Can you verify if [this branch](https://github.com/AvitalTamir/cyphernetes/tree/91-add-relationship-between-volumeattachments-and-persistentvolumes) works?

**Comment by dimm0** [comment]
I'd wait for a brew release if possible :) It probably is
Doing regular grep/awk/sed stuff for now while fixing stuff...

**Comment by AvitalTamir** [comment]
Got it! So thanks for reporting, I'll have this covered one way or another in the next release :)

**Comment by dimm0** [comment]
Great :) and I'll keep trying using it for my cluster debugging
I love the idea!

**Comment by AvitalTamir** [comment]
Thank you so much for all the feedback, this is very exciting stuff for me

**Comment by AvitalTamir** [comment]
resolved by #95

**Comment by AvitalTamir** [comment]
Resolved by #95
